"""Tests for Descrybe -> feed curation: the transform + the dedup flag."""
import sys
from pathlib import Path

RADAR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(RADAR))

import curate

DESCRYBE = [
    {"title": "Park v. Kim", "citation": "91 F.4th 610",
     "court": "Court of Appeals for the Second Circuit",
     "decision_date": "2024-01-30", "case_id": "c1",
     "body": "Sanctioned for citing nonexistent cases generated by ChatGPT.",
     "url": "https://descrybe.com/share/1"},
    {"title": "Mata v. Avianca, Inc.", "citation": "678 F. Supp. 3d 443",
     "court": "District Court, S.D. New York", "decision_date": "2023-06-22",
     "case_id": "c2", "body": "Rule 11 sanctions for fabricated ChatGPT citations.",
     "url": "https://descrybe.com/share/2",
     "opinion_type": "Unknown (100trialcourt)"},
    {"title": "", "citation": "x", "decision_date": "2024-01-01"},  # dropped: no title
]


def test_transform_fields():
    items = curate.descrybe_to_items(DESCRYBE, ["disclosure"])
    assert len(items) == 2          # empty-title entry dropped
    i = items[0]
    assert i["title"] == "Park v. Kim"
    assert i["tier"] == "T1"
    assert i["citation"] == "91 F.4th 610"
    assert i["source"] == "Court of Appeals for the Second Circuit"
    assert i["fault_lines"] == ["disclosure"]
    assert i["date"] == "2024-01-30"


def test_trial_court_flagged_for_review():
    items = curate.descrybe_to_items(DESCRYBE, ["disclosure"])
    assert items[1]["review"] == "trial court — confirm tier"


def test_in_kb_flag_detects_duplicate():
    # "Mata v. Avianca, Inc." matches the KB's "Mata v. Avianca — Rule 11 ..." (base
    # name match ignoring the "Inc."/"—" suffixes). A genuinely-new case flags False.
    items = curate.descrybe_to_items(DESCRYBE, ["disclosure"])
    assert items[1]["in_kb"] is True    # Mata is a known KB item
    fresh = [{"title": "Totally New Case v. Nobody", "citation": "999 U.S. 1",
              "court": "x", "decision_date": "2026-01-01", "case_id": "c",
              "body": "x", "url": "x"}]
    assert curate.descrybe_to_items(fresh, ["disclosure"])[0]["in_kb"] is False


def test_distinct_statutes_same_prefix_not_dupes():
    """Two statutes sharing a prefix ('Colorado AI Act —') but with different citations
    (§ 6-1-1704 vs § 6-1-1706) must NOT be deduped against each other."""
    items = [
        {"date": "2026-01-01", "tier": "T1", "title": "Colorado AI Act — consumer disclosure",
         "source": "x", "url": "https://x", "citation": "Colo. Rev. Stat. § 6-1-1704",
         "fault_lines": ["convergence"], "text": "disclose AI", "empirical": False, "conflict": False},
        {"date": "2026-01-01", "tier": "T1", "title": "Colorado AI Act — ISO 42001 defense",
         "source": "x", "url": "https://x", "citation": "Colo. Rev. Stat. § 6-1-1706",
         "fault_lines": ["convergence"], "text": "affirmative defense", "empirical": False, "conflict": False},
    ]
    # distinct citations -> both are new relative to each other
    assert curate._already_in_kb(items[1], [items[0]]) is False


def _sandbox_ledger(tmp_path):
    """Point the admission ledger at a temp file so admit() tests don't pollute the real one."""
    import ledger
    ledger.ADMISSIONS_FILE = tmp_path / "admissions.jsonl"
    ledger.HISTORY = tmp_path


def test_admit_writes_curated_feed(tmp_path):
    """admit() writes feed-schema rows (flat fault_lines, no harvested flag, citation kept)."""
    import json
    _sandbox_ledger(tmp_path)
    feed = tmp_path / "feed.jsonl"
    items = [{"date": "2026-01-01", "tier": "T1", "title": "Totally New Case v. Nobody",
              "source": "Court", "url": "https://x", "citation": "999 U.S. 1",
              "fault_lines": ["disclosure"], "text": "AI disclosure required.",
              "empirical": False, "conflict": False}]
    written = curate.admit(items, feed_path=feed)
    assert len(written) == 1
    row = json.loads(feed.read_text().splitlines()[0])
    assert row["fault_lines"] == ["disclosure"]       # flat list, not nested
    assert "harvested" not in row                     # curated, not machine-fetched
    assert row["citation"] == "999 U.S. 1"


def test_admit_skips_kb_duplicate(tmp_path):
    """admit() skips a case already in the KB."""
    _sandbox_ledger(tmp_path)
    feed = tmp_path / "feed.jsonl"
    items = [{"date": "2023-06-22", "tier": "T1", "title": "Mata v. Avianca, Inc.",
              "source": "x", "url": "https://x", "citation": "", "fault_lines": ["disclosure"],
              "text": "already in KB", "empirical": False, "conflict": False}]
    written = curate.admit(items, feed_path=feed)
    assert written == []                              # Mata is already in the curated feed


def test_admit_records_to_ledger(tmp_path):
    """admit() records a 'curated' decision to the audit ledger — the run-to-run memory."""
    import ledger
    _sandbox_ledger(tmp_path)
    feed = tmp_path / "feed.jsonl"
    items = [{"date": "2026-01-01", "tier": "T1", "title": "Brand New Ruling v. Z",
              "source": "Court", "url": "https://descrybe.com/share/x", "citation": "",
              "fault_lines": ["verification"], "text": "verify citations",
              "empirical": False, "conflict": False}]
    curate.admit(items, feed_path=feed)
    rows = ledger.load_admissions()
    assert any(r["decision"] == "curated" and "Brand New Ruling" in r["title"] for r in rows)
    # and it is now "already decided", so a re-run skips it
    assert ledger.already_decided(items[0])


def test_mark_reviewed_roundtrip(tmp_path):
    """mark_reviewed writes today's date; load_reviewed reads it back (dormant vs neglected)."""
    import score
    from datetime import date
    reviewed_file = tmp_path / "reviewed.json"
    orig_score = score.REVIEWED_PATH
    orig_curate = curate.REVIEWED_PATH
    score.REVIEWED_PATH = reviewed_file
    curate.REVIEWED_PATH = reviewed_file
    try:
        r = curate.mark_reviewed(['fees', 'insurance'])
        assert r['fees'] == date.today().isoformat()
        assert score.load_reviewed()['insurance'] == date.today().isoformat()
    finally:
        score.REVIEWED_PATH = orig_score
        curate.REVIEWED_PATH = orig_curate


if __name__ == "__main__":
    import tempfile
    tests = [v for k, v in sorted(globals().items())
             if k.startswith("test_") and callable(v)]
    passed = 0
    for t in tests:
        try:
            if t.__code__.co_argcount:
                with tempfile.TemporaryDirectory() as d:
                    t(Path(d))
            else:
                t()
            print(f"PASS {t.__name__}")
            passed += 1
        except Exception:
            print(f"FAIL {t.__name__}")
            import traceback; traceback.print_exc()
    print(f"\n{passed}/{len(tests)} passed")
    sys.exit(0 if passed == len(tests) else 1)
