#!/usr/bin/env python3
"""
Verify Solomon Stage 2 completion
Check if system instructions were generated
"""
import sys

print("🔍 Checking Solomon Stage 2 Status")
print()
print("To verify Stage 2 completed, check the following in Supabase:")
print()
print("=" * 70)
print("1. CHECK interview_extractions table:")
print("=" * 70)
print()
print("   SELECT id, client_id, status, created_at")
print("   FROM interview_extractions")
print("   ORDER BY created_at DESC")
print("   LIMIT 2;")
print()
print("   ✅ Look for:")
print("      - Most recent record has client_id populated (not NULL)")
print("      - status = 'completed' or 'extraction_complete'")
print()
print("=" * 70)
print("2. CHECK solomon_reviews table:")
print("=" * 70)
print()
print("   SELECT id, extraction_id, status, created_at,")
print("          LENGTH(generated_instructions) as instructions_length")
print("   FROM solomon_reviews")
print("   ORDER BY created_at DESC")
print("   LIMIT 1;")
print()
print("   ✅ Look for:")
print("      - New record created recently")
print("      - generated_instructions is NOT NULL")
print("      - instructions_length > 5000 characters")
print("      - status = 'pending' or 'pending_admin'")
print()
print("=" * 70)
print("3. CHECK function selection:")
print("=" * 70)
print()
print("   SELECT extraction_id, generated_instructions")
print("   FROM solomon_reviews")
print("   ORDER BY created_at DESC")
print("   LIMIT 1;")
print()
print("   Then search in generated_instructions for:")
print("      - '<function name=' (should appear 5 times)")
print("      - Look for which 5 functions were selected")
print()
print("   Expected for Charlie Motor based on interview:")
print("      1. Conceptual_Modeler (Visionary + Architect)")
print("      2. Signal_Analyzer (workload bottleneck)")
print("      3. Independence_Identifier (delegation pain)")
print("      4. Feedback_Drafter (coaching pain point)")
print("      5. Decision_Accelerator or Goal_Tracker")
print()
print("=" * 70)
print("4. QUICK CHECK - Did Stage 2 succeed?")
print("=" * 70)
print()
print("   If solomon_reviews has a new record → ✅ Stage 2 SUCCEEDED")
print("   If no new record → ❌ Stage 2 FAILED or didn't run")
print()
print("=" * 70)
print()

# Ask what they saw
print("What did the injection script output show?")
print()
print("Did you see:")
print("  - Extraction ID: [UUID]?")
print("  - Solomon Status: completed?")
print("  - Any mention of Stage 2 or system instructions?")
print()
